version: "3"
services:
  api:
    build: .
    ports:
    #- <port on localhost>:<port on container>
      - 8000:8000
    # Bind Mount - any changes to source code on local machine will propagate to docker running instance
    # Syncs both folders
    # Add 'ro' to indicate container can't change any of local machine files
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #     - ./.env
    environment:
        # postgres value resolves to the IP address of the container below
        - DATABASE_HOSTNAME=postgres
        - DATABASE_PORT=5432
        - DATABASE_PASSWORD=devon
        - DATABASE_NAME=fastapi
        - DATABASE_USERNAME=postgres
        - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
        - ALGORITHM=HS256
        - ACCESS_TOKEN_EXPIRE_MINUTES=30
    # Overrides Dockerfile; We don't want to add 'reload' to dockerfile since this wouldn't
    # be in production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devon
      - POSTGRES_DB=fastapi

    volumes:
    #this is the path in the container that postgres will write to
    # We want to copy this and save onto our local machine
      - postgres-db:/var/lib/postgresql/data
    # Copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


#Define named volume
volumes:
  postgres-db: